### PR TITLE
support store.action method if available

### PR DESCRIPTION
**Pull request by huygn**
makes running redux-bundler in worker easier.

follows https://github.com/HenrikJoreteg/redux-bundler-preact/blob/6bf10cacc7433d710e4a9be86b42d5694f7262e8/src/index.js

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
Cool, I'll merge this. Hey, by the way, @huygn would you have any interest in being a maintainer of this project? I almost always use Preact these days and I'd rather this be maintained by someone who's actually using it.

**Comment by HenrikJoreteg** [comment]
published to npm as `v1.0.1` thanks @huygn!

**Comment by huygn** [comment]
@HenrikJoreteg 100% would love to. I also have a render-props version of the connect HOC for React that I use internally and would love to put it mainstream 💃

**Comment by HenrikJoreteg** [comment]
@huygn sorry it took me a few days to get back to this, i've given you access to both npm and github for this project. Please just try to keep things in line with the original goals of keeping things as fast/light and simple as possible. Thanks!

**Comment by huygn** [comment]
@HenrikJoreteg Thanks!

**Pull request merged**
